const hangmanWords = {
  1: { word: 'javascript', hint: 'Programming language for the web' },
  2: { word: 'elephant', hint: 'Large mammal with a trunk' },
  3: { word: 'pineapple', hint: 'Tropical fruit with a spiky skin' },
  4: { word: 'mountain', hint: 'High landform with peaks' },
  5: { word: 'umbrella', hint: 'Used to shield from rain or sun' },
  6: { word: 'kangaroo', hint: 'Australian marsupial with a pouch' },
  7: { word: 'keyboard', hint: 'Input device for computers' },
  8: { word: 'hamburger', hint: 'Popular fast-food item' },
  9: { word: 'giraffe', hint: 'Tall, long-necked African mammal' },
  10: { word: 'watermelon', hint: 'Large, juicy fruit with seeds' },
  11: { word: 'symphony', hint: 'Orchestral composition' },
  12: { word: 'caterpillar', hint: 'Larval stage of a butterfly' },
  13: { word: 'treasure', hint: 'Hidden valuable items' },
  14: { word: 'volcano', hint: 'Mountain that erupts with lava' },
  15: { word: 'whisper', hint: 'Soft spoken words' },
  16: { word: 'fireworks', hint: 'Colorful explosions in the sky' },
  17: { word: 'accordion', hint: 'Musical instrument with bellows' },
  18: {
    word: 'quarantine',
    hint: 'Isolation period to prevent disease spread',
  },
  19: { word: 'detective', hint: 'Investigative professional' },
  20: { word: 'puzzle', hint: 'A challenging problem to solve' },
  21: { word: 'jungle', hint: 'Dense, tropical forest' },
  22: { word: 'guitar', hint: 'Six-string musical instrument' },
  23: {
    word: 'sculpture',
    hint: 'Artistic creation using materials like clay or stone',
  },
  24: { word: 'butterfly', hint: 'Colorful insect with wings' },
  25: { word: 'astronomy', hint: 'Study of celestial objects and phenomena' },
  26: { word: 'carousel', hint: 'Merry-go-round amusement ride' },
  27: { word: 'waterfall', hint: 'Natural downward flow of water' },
  28: { word: 'cinnamon', hint: 'Spice with a sweet and warm flavor' },
  29: { word: 'shampoo', hint: 'Hair-cleaning product' },
  30: { word: 'saxophone', hint: 'Brass instrument with a curved shape' },
  31: { word: 'mosquito', hint: 'Small flying insect that bites' },
  32: { word: 'ostrich', hint: 'Large flightless bird with long legs' },
  33: { word: 'chocolate', hint: 'Sweet, brown confection made from cocoa' },
  34: { word: 'galaxy', hint: 'Vast system of stars, gas, and dust' },
  35: { word: 'wristwatch', hint: 'Timekeeping device worn on the wrist' },
  36: { word: 'symmetric', hint: 'Mirror-image balance' },
  37: { word: 'accordion', hint: 'Musical instrument with bellows' },
  38: { word: 'marathon', hint: 'Long-distance running race' },
  39: { word: 'notebook', hint: 'Bound collection of pages for writing' },
  40: { word: 'dolphin', hint: 'Intelligent marine mammal' },
  41: {
    word: 'harmonica',
    hint: 'Small musical instrument played with the mouth',
  },
  42: { word: 'gallop', hint: "Horse's fast running gait" },
  43: { word: 'backpack', hint: 'Bag carried on the back' },
  44: { word: 'chandelier', hint: 'Decorative hanging light fixture' },
  45: { word: 'cucumber', hint: 'Green vegetable with a mild flavor' },
  46: {
    word: 'syndrome',
    hint: 'Group of symptoms indicating a particular condition',
  },
  47: { word: 'adventure', hint: 'Exciting and daring experience' },
  48: {
    word: 'macaroon',
    hint: 'Sweet cookie made with coconut or almond flour',
  },
  49: {
    word: 'telescope',
    hint: 'Optical instrument for distant observation of celestial objects',
  },
  50: { word: 'mysterious', hint: 'Difficult to understand or explain' },
  51: { word: 'gazelle', hint: 'Graceful and swift African antelope' },
  52: {
    word: 'television',
    hint: 'Electronic device for broadcasting audiovisual content',
  },
  53: { word: 'galactic', hint: 'Related to a galaxy or galaxies' },
  54: { word: 'xylophone', hint: 'Musical instrument with wooden bars' },
  55: { word: 'silhouette', hint: 'Outline or shadow of a person or object' },
  56: { word: 'kettle', hint: 'Container for boiling water' },
  57: { word: 'magnificent', hint: 'Exceptionally beautiful or impressive' },
  58: {
    word: 'navigate',
    hint: 'Plan and direct the route of a ship or aircraft',
  },
  59: {
    word: 'whistle',
    hint: 'Device for making a shrill sound by blowing air through it',
  },
  60: { word: 'vibrant', hint: 'Full of energy and life' },
  61: { word: 'carousel', hint: 'Amusement ride with spinning seats' },
  62: { word: 'gondola', hint: 'Narrow boat used in Venetian canals' },
  63: {
    word: 'lighthouse',
    hint: 'Tall structure with a light to guide ships',
  },
  64: { word: 'pinecone', hint: 'Seed cone from a pine tree' },
  65: {
    word: 'parachute',
    hint: 'Device for slowing descent from an aircraft',
  },
  66: { word: 'symphony', hint: 'Orchestral musical composition' },
  67: { word: 'infinity', hint: 'Endless or limitless' },
  68: { word: 'illusion', hint: 'Deceptive appearance or impression' },
  69: { word: 'cappuccino', hint: 'Coffee with steamed milk and foam' },
  70: { word: 'onomatopoeia', hint: 'Words imitating natural sounds' },
  71: { word: 'portfolio', hint: 'Collection of artistic works or documents' },
  72: {
    word: 'serendipity',
    hint: 'Unexpected discovery of something pleasant',
  },
  73: { word: 'whisker', hint: "Long, stiff hair on an animal's face" },
  74: { word: 'keyboard', hint: 'Input device for computers' },
  75: { word: 'kangaroo', hint: 'Australian marsupial with a pouch' },
  76: { word: 'jigsaw', hint: 'Puzzle with irregularly shaped pieces' },
  77: { word: 'vagabond', hint: 'Wanderer with no permanent home' },
  78: { word: 'umbrella', hint: 'Canopy used for protection against rain' },
  79: { word: 'network', hint: 'Interconnected system or group' },
  80: { word: 'symmetrical', hint: 'Mirror-image balance' },
  81: { word: 'marathon', hint: 'Long-distance running race' },
  82: { word: 'xylophone', hint: 'Musical instrument with wooden bars' },
  83: { word: 'grandiose', hint: 'Pompous or extravagant in appearance' },
  84: { word: 'volcano', hint: 'Mountain that erupts with lava' },
  85: { word: 'trampoline', hint: 'Bouncing apparatus for exercise or play' },
  86: { word: 'boulevard', hint: 'Wide street in a city' },
  87: {
    word: 'penguin',
    hint: 'Flightless bird found in the Southern Hemisphere',
  },
  88: { word: 'champion', hint: 'Winner or top performer in a competition' },
  89: { word: 'watermelon', hint: 'Large, juicy fruit with seeds' },
  90: { word: 'accordion', hint: 'Musical instrument with bellows' },
  91: { word: 'whisper', hint: 'Soft spoken words' },
  92: { word: 'bicycle', hint: 'Two-wheeled vehicle powered by pedaling' },
  93: {
    word: 'quarantine',
    hint: 'Isolation period to prevent disease spread',
  },
  94: { word: 'detective', hint: 'Investigative professional' },
  95: { word: 'flamingo', hint: 'Tall, pink wading bird' },
  96: { word: 'symphony', hint: 'Orchestral composition' },
  97: { word: 'marvelous', hint: 'Extremely good or impressive' },
  98: { word: 'chocolate', hint: 'Sweet, brown confection made from cocoa' },
  99: { word: 'shampoo', hint: 'Hair-cleaning product' },
  100: { word: 'radiant', hint: 'Shining brightly; emitting light or heat' },
};

export default hangmanWords;
